Organizations:

  - &Org1
    Name: Org1MSP
    ID: Org1MSP

    MSPDir: ../identities/org-admin/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"

      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"

      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"

    OrdererEndpoints:
      - orderer0:7050


Capabilities:

  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_0: true


Application:

  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"

    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"

    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ApplicationCapabilities


Orderer:

  OrdererType: etcdraft

  Addresses:
    - orderer0:7050

  BatchTimeout: 2s

  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB

  Organizations:
    - *Org1

  EtcdRaft:
    Consenters:

      - Host: orderer0
        Port: 7050
        ClientTLSCert: ../identities/orderer0/tls/signcerts/cert.pem
        ServerTLSCert: ../identities/orderer0/tls/signcerts/cert.pem

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"

    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"

    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

  Capabilities:
    <<: *OrdererCapabilities


Channel: &ChannelDefaults

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"

    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"

    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ChannelCapabilities


Profiles:

  XITChannel:

    <<: *ChannelDefaults

    Consortium: SampleConsortium

    Application:

      Organizations:
        - *Org1

      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"

        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"

        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"

      Capabilities:
        <<: *ApplicationCapabilities

  XITGenesis:

    <<: *ChannelDefaults

    Orderer:
      OrdererType: etcdraft

      Addresses:
        - orderer0:7050

      BatchTimeout: 2s

      BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

      Organizations:
        - *Org1

      EtcdRaft:
        Consenters:

          - Host: orderer0
            Port: 7050
            ClientTLSCert: ../identities/orderer0/tls/signcerts/cert.pem
            ServerTLSCert: ../identities/orderer0/tls/signcerts/cert.pem

      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"

        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"

        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"

        BlockValidation:
          Type: ImplicitMeta
          Rule: "ANY Writers"

      Capabilities:
        <<: *OrdererCapabilities

    Consortiums:

      SampleConsortium:
        Organizations:
          - *Org1
